---
title: "My First Blog"
date: 2019-12-03
---
author: Biraja Prasad Nayak
email: birajanaya@gmail.com
description: > Hi All This my new blog.

# social links
twitter_username: N/A
github_username:  birajanaya@gmail.com

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
-------------
